initial commit
singnet/snet-admin-dapp pull request #1
Opened 2019-05-23 06:06 UTC by Vivek205

Features available as of now:

- Getting daemon endpoint.
- Authorizing signature.
- Viewing configs of the daemon.
- Categorizing the configs based on the section.
- Stopping daemon for accepting requests.
- Starting daemon to accept further requests.

2019-06-07 09:03 UTC, raamb requested changes

2019-06-07 09:03 UTC, raamb commented on src/pages/connectWallet/ConnectWallet.tsx
> +                                <div className="col-xs-12 col-sm-12 col-md-12 col-lg-12 overview-text">SingularityNET is an open and decentralized network of AI services made accessible through block
This text is not relevant to the admin dapp. Lets change it

2019-06-07 09:03 UTC, raamb commented on src/pages/connectWallet/ConnectWallet.tsx
> +                                        This Dapp allows you to browse the list of SingularityNET Agents from the SingularityNET Registry. You need a Metamask wallet to invoke a service.<br /><br />
This text is not relevant to the admin dapp. Lets change it

2019-06-07 09:03 UTC, raamb commented on src/protos/config/config.proto
> +syntax = "proto3";
Lets have this file autogenerated by a build script

2019-06-07 09:03 UTC, raamb commented on src/pages/connectWallet/ConnectWallet.tsx
> +                                <h1><a href="/SampleServices" title="SingularityNET"><span className="icon-logo"></span></a></h1>
Is there a component called SampleServices?

2019-06-07 09:03 UTC, raamb commented on src/assets/css/profile.css
> +
The MUI styles do not seem right. Is this used anywhere?

2019-06-07 09:03 UTC, raamb commented on src/utilities/util.js
> +/* eslint-disable @typescript-eslint/no-var-requires */
Is this file used?

2019-06-07 09:03 UTC, raamb commented on src/utilities/service_state.js
> +export const serviceStateJSON = {
Do you need this?

2019-06-07 09:03 UTC, raamb commented on src/utilities/networks.ts
> +export const NETWORKS: networks = {
Why do you need this?

2019-06-07 09:03 UTC, raamb commented on src/utilities/ChannelHelper.js
> +import { base64ToHex } from './util'
Why do you need this?

2019-06-07 09:03 UTC, raamb commented on src/utilities/BlockChainHelper.js
> +export default class BlockchainHelper {
Do you need all methods of this class?

2019-06-07 09:03 UTC, raamb commented on README.md
> +This project was bootstrapped with [Create React App](https://github.com/facebook/create-react-app).
Can we include a linter?

2019-06-07 11:21 UTC, Vivek205 commented on README.md
> +This project was bootstrapped with [Create React App](https://github.com/facebook/create-react-app).
Included eslint-prettier for linting.

2019-06-07 12:55 UTC, Vivek205 commented on src/pages/connectWallet/ConnectWallet.tsx
> +                                <h1><a href="/SampleServices" title="SingularityNET"><span className="icon-logo"></span></a></h1>
Removed

2019-06-07 12:59 UTC, Vivek205 commented on src/protos/config/config.proto
> +syntax = "proto3";
Created an issue for it. Will work on that.

2019-06-10 10:21 UTC, Vivek205 commented on src/utilities/BlockChainHelper.js
> +export default class BlockchainHelper {
removed unused methods

2019-06-10 11:28 UTC, raamb commented on src/pages/operator/StartStopDaemon.tsx
> +                  showAlert: true,
Lets have all messages in its own file so there is only one place to modify it and also support translations if required in future

2019-06-11 05:50 UTC, raamb commented on src/pages/operator/InputsContainer.tsx
> +  private shouldActionsDisabled = (): boolean => {
Lets call it shouldActionsBeDisabled

2019-06-11 05:50 UTC, raamb commented on src/pages/operator/InputsContainer.tsx
> +      // return true;  revert back
Should this return true? Currently this method always returns false

2019-06-11 05:51 UTC, raamb commented on src/pages/operator/InputsContainer.tsx
> +      <>
What does the above empty tag mean?

2019-06-11 05:52 UTC, raamb commented on src/pages/daemonEndpoint/GetDaemonEndpoint.tsx
> +
Can we move all styles into its own file outside? Whats the best practise for this?

2019-06-11 05:54 UTC, raamb commented on src/pages/operator/InputsContainer.tsx
> +                    if (config.type === 1) {
Lets use an ENUM instead of a number, so instead of 1 lets say TYPE.NUMBER or something like that

2019-06-11 05:56 UTC, raamb commented on src/pages/operator/StartStopDaemon.tsx
> +    let command = daemonRunning ? 1 : 0; // 1 - Stop Request, 0 - Start Request
Lets use an enum for daemonRunning

2019-06-11 07:05 UTC, raamb commented on src/reusableComponents/Error.tsx
> +            {/* <Button
Should this code be commented?

2019-06-11 07:06 UTC, raamb commented on src/reusableComponents/Header.tsx
> +    chainId: 42
Use a networks ENUM

2019-06-11 07:12 UTC, raamb commented on src/reusableComponents/Header.tsx
> +                    <h1>
Which component is SampleServices?

2021-05-19 06:54 UTC, closed without merging